### ISSUE TITLE
some flakiness

### ISSUE THREAD

**Issue by NareshDealer** [ChrisBall/CAP1298#1]
Hi,
Recently we have started using CAP1298 for one of our project and found your library while searching if there are any ready to use.

You mentioned there is some flakiness in chip.. Can you elaborate what is the meaning of flakiness in your experience with this chip.
Also would like to know if you overcame the issue with some other modifications or if you moved away from this chip.
If you moved away, what is the other option ( chip ) you have adopted .?

Also curious to know how did you used this chip in your project.. means as a capacitive touch pad or some other ways.?

**Comment by ChrisBall** [comment]
the touch sensor does not have separate touch/release thresholds, meaning touches can be noisy, and the chips autoconfiguration settings (which cannot be turned off) mean that long touches (10s+) will be switched off. It's alright for making a basic keypad, but not for my purposes (musical instruments)

I eventually switched back to using the obsolete MPR121, which can still be bought in quantity.

**Comment by jwktje** [comment]
Hey @ChrisBall 
I'm researching CapSense IC's for musical instruments and stumbled upon this Issue. 
What is your advice at the moment for this? I found out the MPR121 was discontinued so found the CAP1298 and this library.

I'd love to just use I2C and read analog touch values. Are you still using the MPR121 in projects going forward?

**Comment by ChrisBall** [comment]
Hey!

I was working on a project designing a production PCB at the time I wrote this library, and was looking for an MPR121 replacement too. Eventually I realised that while "obsolete", it's still easy enough to buy MPR121 touch ICs from China (although they could be counterfeits). 
If you're making thousands of PCBs you can still buy full reels (as there was a company who bought the rights to produce it), if not you can still buy small strips quite cheaply from chinese manufacturers/stockists. Basic MPR121 modules are still very affordable. 

I haven't done any research for a while, but when I last checked the MPR121 was still the best option for me, in terms of cost and capability.

Please let me know if you find a good replacement!

**Comment by jwktje** [comment]
Good to know! In that case the MPR121 is still a good choice I guess.
What is the output like? Can you read a range of values or is it just touched/not-touched?

For my instrument I would love to have a more detailed reading that a boolean one.

**Comment by ChrisBall** [comment]
You can read a range of values, yes - the sensitivity/update rate/filtering are all adjustable, and if you have a large touch surface you can usually read changes long before an actual touch. It also has a proximity reading, which is the output from all touch electrodes.
